
package org.oscarehr.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-22T19:32:55.049-08:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "Exception", targetNamespace = "http://ws.oscarehr.org/")
public class Exception_Exception extends java.lang.Exception {
    
    private org.oscarehr.ws.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, org.oscarehr.ws.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, org.oscarehr.ws.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public org.oscarehr.ws.Exception getFaultInfo() {
        return this.exception;
    }
}
