package org.oscarehr.ws;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-22T19:32:55.068-08:00
 * Generated source version: 3.1.4
 * 
 */

@WebService(targetNamespace = "http://ws.oscarehr.org/", name = "HL7LabUploadWs")
@XmlSeeAlso({ObjectFactory.class})
public interface HL7LabUploadWs {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "parseHL7", targetNamespace = "http://ws.oscarehr.org/", className = "org.oscarehr.ws.ParseHL7")
    @WebMethod
    @ResponseWrapper(localName = "parseHL7Response", targetNamespace = "http://ws.oscarehr.org/", className = "org.oscarehr.ws.ParseHL7Response")
    public boolean parseHL7(
        @WebParam(name = "className", targetNamespace = "")
        java.lang.String className,
        @WebParam(name = "savedPath", targetNamespace = "")
        java.lang.String savedPath,
        @WebParam(name = "fileId", targetNamespace = "")
        int fileId,
        @WebParam(name = "labType", targetNamespace = "")
        java.lang.String labType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveHL7", targetNamespace = "http://ws.oscarehr.org/", className = "org.oscarehr.ws.SaveHL7")
    @WebMethod
    @ResponseWrapper(localName = "saveHL7Response", targetNamespace = "http://ws.oscarehr.org/", className = "org.oscarehr.ws.SaveHL7Response")
    public int saveHL7(
        @WebParam(name = "savedFileName", targetNamespace = "")
        java.lang.String savedFileName,
        @WebParam(name = "providerNumber", targetNamespace = "")
        java.lang.String providerNumber
    ) throws Exception_Exception;
}
