package org.oscarehr.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-22T19:32:55.077-08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "HL7LabUploadWsService", 
                  wsdlLocation = "http://127.0.0.1:8080/oscar-12.1.1-SNAPSHOT/ws/HL7LabUpload?wsdl",
                  targetNamespace = "http://ws.oscarehr.org/") 
@HandlerChain(file = "/handler-chain.xml")
public class HL7LabUploadWsService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ws.oscarehr.org/", "HL7LabUploadWsService");
    public final static QName HL7LabUploadWsPort = new QName("http://ws.oscarehr.org/", "HL7LabUploadWsPort");
    
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/oscar-12.1.1-SNAPSHOT/ws/HL7LabUpload?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HL7LabUploadWsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/oscar-12.1.1-SNAPSHOT/ws/HL7LabUpload?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HL7LabUploadWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HL7LabUploadWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HL7LabUploadWsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HL7LabUploadWsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HL7LabUploadWsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HL7LabUploadWsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HL7LabUploadWs
     */
    @WebEndpoint(name = "HL7LabUploadWsPort")
    public HL7LabUploadWs getHL7LabUploadWsPort() {
        return super.getPort(HL7LabUploadWsPort, HL7LabUploadWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HL7LabUploadWs
     */
    @WebEndpoint(name = "HL7LabUploadWsPort")
    public HL7LabUploadWs getHL7LabUploadWsPort(WebServiceFeature... features) {
        return super.getPort(HL7LabUploadWsPort, HL7LabUploadWs.class, features);
    }

}
