
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.oscarehr.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-22T21:56:17.529-08:00
 * Generated source version: 3.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "LoginWsService",
                      portName = "LoginWsPort",
                      targetNamespace = "http://ws.oscarehr.org/",
                      wsdlLocation = "http://127.0.0.1:8080/oscar-12.1.1-SNAPSHOT/ws/LoginService?wsdl",
                      endpointInterface = "org.oscarehr.ws.LoginWs")
                      
public class LoginWsPortImpl implements LoginWs {

    private static final Logger LOG = Logger.getLogger(LoginWsPortImpl.class.getName());

    /* (non-Javadoc)
     * @see org.oscarehr.ws.LoginWs#login(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public org.oscarehr.ws.LoginResultTransfer login(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation login");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            org.oscarehr.ws.LoginResultTransfer _return = new org.oscarehr.ws.LoginResultTransfer();
            _return.setSecurityId(Integer.valueOf(1862129707));
            _return.setSecurityTokenKey("SecurityTokenKey-1683960656");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NotAuthorisedException_Exception("NotAuthorisedException...");
    }

}
