package org.oscarehr.ws;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-22T21:56:17.539-08:00
 * Generated source version: 3.1.4
 * 
 */
@HandlerChain(file = "handler-chain.xml")
@WebService(targetNamespace = "http://ws.oscarehr.org/", name = "LoginWs")
@XmlSeeAlso({ObjectFactory.class})
public interface LoginWs {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://ws.oscarehr.org/", className = "org.oscarehr.ws.Login")
    @WebMethod
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ws.oscarehr.org/", className = "org.oscarehr.ws.LoginResponse")
    public org.oscarehr.ws.LoginResultTransfer login(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
