
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.oscarehr.ws;

import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-22T19:32:55.056-08:00
 * Generated source version: 3.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "HL7LabUploadWsService",
                      portName = "HL7LabUploadWsPort",
                      targetNamespace = "http://ws.oscarehr.org/",
                      wsdlLocation = "http://127.0.0.1:8080/oscar-12.1.1-SNAPSHOT/ws/HL7LabUpload?wsdl",
                      endpointInterface = "org.oscarehr.ws.HL7LabUploadWs")                     
public class HL7LabUploadWsPortImpl implements HL7LabUploadWs {

    private static final Logger LOG = Logger.getLogger(HL7LabUploadWsPortImpl.class.getName());

    /* (non-Javadoc)
     * @see org.oscarehr.ws.HL7LabUploadWs#parseHL7(java.lang.String  className ,)java.lang.String  savedPath ,)int  fileId ,)java.lang.String  labType )*
     */
    public boolean parseHL7(java.lang.String className,java.lang.String savedPath,int fileId,java.lang.String labType) { 
        LOG.info("Executing operation parseHL7");
        System.out.println(className);
        System.out.println(savedPath);
        System.out.println(fileId);
        System.out.println(labType);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.oscarehr.ws.HL7LabUploadWs#saveHL7(java.lang.String  savedFileName ,)java.lang.String  providerNumber )*
     */
    public int saveHL7(java.lang.String savedFileName,java.lang.String providerNumber) throws Exception_Exception    { 
        LOG.info("Executing operation saveHL7");
        System.out.println(savedFileName);
        System.out.println(providerNumber);
        try {
            int _return = -793062364;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
