
package org.oscarehr.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-22T19:32:55.009-08:00
 * Generated source version: 3.1.4
 * 
 */
public final class HL7LabUploadWs_HL7LabUploadWsPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.oscarehr.org/", "HL7LabUploadWsService");

    private HL7LabUploadWs_HL7LabUploadWsPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HL7LabUploadWsService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HL7LabUploadWsService ss = new HL7LabUploadWsService(wsdlURL, SERVICE_NAME);
        HL7LabUploadWs port = ss.getHL7LabUploadWsPort();  
        
        {
        System.out.println("Invoking parseHL7...");
        java.lang.String _parseHL7_className = "_parseHL7_className1416295668";
        java.lang.String _parseHL7_savedPath = "_parseHL7_savedPath2056139005";
        int _parseHL7_fileId = 534762262;
        java.lang.String _parseHL7_labType = "_parseHL7_labType-2016456432";
        boolean _parseHL7__return = port.parseHL7(_parseHL7_className, _parseHL7_savedPath, _parseHL7_fileId, _parseHL7_labType);
        System.out.println("parseHL7.result=" + _parseHL7__return);


        }
        {
        System.out.println("Invoking saveHL7...");
        java.lang.String _saveHL7_savedFileName = "_saveHL7_savedFileName-876587189";
        java.lang.String _saveHL7_providerNumber = "_saveHL7_providerNumber-531763251";
        try {
            int _saveHL7__return = port.saveHL7(_saveHL7_savedFileName, _saveHL7_providerNumber);
            System.out.println("saveHL7.result=" + _saveHL7__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
