package org.oscarehr.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-22T21:56:17.545-08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "LoginWsService", 
                  wsdlLocation = "http://127.0.0.1:8080/oscar-12.1.1-SNAPSHOT/ws/LoginService?wsdl",
                  targetNamespace = "http://ws.oscarehr.org/") 
public class LoginWsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.oscarehr.org/", "LoginWsService");
    public final static QName LoginWsPort = new QName("http://ws.oscarehr.org/", "LoginWsPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/oscar-12.1.1-SNAPSHOT/ws/LoginService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LoginWsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/oscar-12.1.1-SNAPSHOT/ws/LoginService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LoginWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LoginWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginWsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public LoginWsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LoginWsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LoginWsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns LoginWs
     */
    @WebEndpoint(name = "LoginWsPort")
    public LoginWs getLoginWsPort() {
        return super.getPort(LoginWsPort, LoginWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginWs
     */
    @WebEndpoint(name = "LoginWsPort")
    public LoginWs getLoginWsPort(WebServiceFeature... features) {
        return super.getPort(LoginWsPort, LoginWs.class, features);
    }

}
