
package org.oscarehr.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-22T21:56:17.475-08:00
 * Generated source version: 3.1.4
 * 
 */
public final class LoginWs_LoginWsPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.oscarehr.org/", "LoginWsService");

    private LoginWs_LoginWsPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LoginWsService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LoginWsService ss = new LoginWsService(wsdlURL, SERVICE_NAME);
        LoginWs port = ss.getLoginWsPort();  
        
        {
        System.out.println("Invoking login...");
        java.lang.String _login_arg0 = "_login_arg01057912881";
        java.lang.String _login_arg1 = "_login_arg1-1751209910";
//        try {
            org.oscarehr.ws.LoginResultTransfer _login__return = port.login(_login_arg0, _login_arg1);
            System.out.println("login.result=" + _login__return);

//        } catch (NotAuthorisedException_Exception e) { 
//            System.out.println("Expected exception: NotAuthorisedException has occurred.");
//            System.out.println(e.toString());
//        }
            }

        System.exit(0);
    }

}
