
package org.oscarehr.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-22T21:56:17.522-08:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "NotAuthorisedException", targetNamespace = "http://ws.oscarehr.org/")
public class NotAuthorisedException_Exception extends java.lang.Exception {
    
    private org.oscarehr.ws.NotAuthorisedException notAuthorisedException;

    public NotAuthorisedException_Exception() {
        super();
    }
    
    public NotAuthorisedException_Exception(String message) {
        super(message);
    }
    
    public NotAuthorisedException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NotAuthorisedException_Exception(String message, org.oscarehr.ws.NotAuthorisedException notAuthorisedException) {
        super(message);
        this.notAuthorisedException = notAuthorisedException;
    }

    public NotAuthorisedException_Exception(String message, org.oscarehr.ws.NotAuthorisedException notAuthorisedException, Throwable cause) {
        super(message, cause);
        this.notAuthorisedException = notAuthorisedException;
    }

    public org.oscarehr.ws.NotAuthorisedException getFaultInfo() {
        return this.notAuthorisedException;
    }
}
