<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="LoginWsService" targetNamespace="http://ws.oscarehr.org/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.oscarehr.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://ws.oscarehr.org/" xmlns:tns="http://ws.oscarehr.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="login" type="tns:login"/>
<xs:element name="loginResponse" type="tns:loginResponse"/>
<xs:complexType name="login">
<xs:sequence>
<xs:element minOccurs="0" name="arg0" type="xs:string"/>
<xs:element minOccurs="0" name="arg1" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="loginResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="tns:loginResultTransfer"/>
</xs:sequence>
</xs:complexType>
<xs:complexType final="extension restriction" name="loginResultTransfer">
<xs:sequence>
<xs:element minOccurs="0" name="securityId" type="xs:int"/>
<xs:element minOccurs="0" name="securityTokenKey" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element name="NotAuthorisedException" type="tns:NotAuthorisedException"/>
<xs:complexType name="NotAuthorisedException">
<xs:sequence/>
</xs:complexType>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="loginResponse">
    <wsdl:part element="tns:loginResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="login">
    <wsdl:part element="tns:login" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="NotAuthorisedException">
    <wsdl:part element="tns:NotAuthorisedException" name="NotAuthorisedException">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="LoginWs">
    <wsdl:operation name="login">
      <wsdl:input message="tns:login" name="login">
    </wsdl:input>
      <wsdl:output message="tns:loginResponse" name="loginResponse">
    </wsdl:output>
      <wsdl:fault message="tns:NotAuthorisedException" name="NotAuthorisedException">
    </wsdl:fault>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="LoginWsServiceSoapBinding" type="tns:LoginWs">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="login">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="login">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="loginResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="NotAuthorisedException">
        <soap:fault name="NotAuthorisedException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="LoginWsService">
    <wsdl:port binding="tns:LoginWsServiceSoapBinding" name="LoginWsPort">
      <soap:address location="https://192.168.2.191:8181/oscar-12.1.1/ws/LoginService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>